version: "3"

services:
  mysql:
    image: mysql:5.6
    container_name: mysql
#    volumes:
#      - "./docker/db-data/:/var/lib/mysql"
#      - "./docker/init/:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: kotlin_docker
      MYSQL_ROOT_PASSWORD: jace1
#      MYSQL_USER: "jace"
#      MYSQL_PASSWORD: "jace"
    ports:
      - 3307:3306
    restart: always


  api:
    image: api
    container_name: api
    ports:
      - 8080:8080
#    volumes:
#      - ./subprojects/api/:/app/api/
    links:
      - grpc
    restart: always


  grpc:
    image: grpc
    container_name: grpc
    ports:
      - 6565:6565
#    volumes:
#      - ./subprojects/grpc/:/app/grpc/
    links:
      - mysql
    restart: always

  frontend:
    image: frontend
    ports:
      - "8000:8000"
#    volumes:
#      - ./subprojects/frontend/:/app/frontend/
    links:
      - api
    restart: always